### ISSUE TITLE
JWT Docs by Atlassian have moved

### ISSUE THREAD

**Issue by phylliswong** [Make-School-Courses/BEW-1.3-Server-Side-Architectures-and-Frameworks#12]
I found this link:
https://developer.atlassian.com/cloud/jira/platform/understanding-jwt/

![screen shot 2018-11-05 at 10 33 19 am](https://user-images.githubusercontent.com/24304039/48018655-46386100-e0e6-11e8-891f-33f8992a5fb8.png)

**Comment by droxey** [comment]
@PhyllisWong thanks! this is now removed.
