### ISSUE TITLE
In the BDD that are provided, it would make more sense to test for an items name, quantity, and price

### ISSUE THREAD

**Issue by DoctaCloak** [Make-School-Courses/BEW-1.3-Server-Side-Architectures-and-Frameworks#8]
### Expected
it('Should create a new item with name, quantity, and price');

### Actual
it('Should create a new item with name and price');

**Comment by DoctaCloak** [comment]
Doing so would make more sense because if you add an item, then the quantity should not be null.

**Comment by droxey** [comment]
Closed; no longer relevant.
